spring:
  session:
    store-type: jdbc
  jwt:
    secret: ckdgusWkd!@#$
  mvc:
    view:
      prefix: templates
      suffix: .html
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/blog?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true&serverTimezone=UTC
    username: kim
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
    port: 6379
    host: 127.0.0.1
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 20MB



cloud:
  aws:
    s3:
      bucket: kimch-blog
    region:
      static: ap-northeast-2
    credentials:
      instanceProfile: true
      useDefaultAwsCredentialsChain: true
    stack:
      auto: false





